# Generated by Django 5.1.6 on 2025-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
