# Generated by Django 5.1.6 on 2025-02-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BR', 'Brazilian hair'), ('PE', 'Peruvian hair'), ('IN', 'India hair'), ('MA', 'Malaysian hair'), ('EU', 'European hair'), ('CH', 'Chinese hair')], default='BR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('H', 'Hot'), ('N', 'New'), ('R', 'Rare')], default='H', max_length=2),
            preserve_default=False,
        ),
    ]
