# Generated by Django 5.1.6 on 2025-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Tsk'),
            preserve_default=False,
        ),
    ]
