# Generated by Django 5.1.6 on 2025-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'CURVY'), ('FS', 'Final Sale'), ('S', 'STRAIGHT'), ('W', 'WAVY')], max_length=3),
        ),
    ]
