# Generated by Django 5.1.6 on 2025-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='static/images/products_images'),
        ),
    ]
